version : 0.0
os : linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: server/deregister_from_elb.sh
    - location: server/stop.sh
      runas: root
  AfterInstall:
    - location: server/sleep.sh
    - location: server/start.sh
    - location: server/register_with_elb.sh
      runas: root
