version : 0.0
os : linux

files:
  - source: index.html
    destination: /var/www/html

permission:
  - object: /var/www/html
    pattern: index.html
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: server/stop.sh
    - location: server/delete-old.sh
  AfterInstall:
    - location: server/sleep.sh
    - location: server/start.sh
