version : 0.0
os : linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: server/stop.sh
    - location: server/delete-old.sh
      runas: root
  AfterInstall:
    - location: server/sleep.sh
    - location: server/start.sh
      runas: root
